name: shelf_hasura_actions
description: Shelf Middleware for Hasura Action.
version: 1.0.2
homepage: https://github.com/Flutterando/shelf_hasura_actions

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: ^1.3.0
  shelf: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.14.4
